create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  name text not null,
  description text default '',
  price integer not null,
  image_url text default '',
  sizes jsonb not null default '["S","M","L"]'::jsonb,
  stock integer not null default 100,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text unique not null,
  customer_name text not null,
  phone text not null,
  email text,
  address text not null,
  city text not null,
  state text not null,
  pincode text not null,
  items jsonb not null,
  subtotal integer not null,
  status text not null default 'pending',
  razorpay_order_id text,
  razorpay_payment_id text,
  shiprocket_tracking_id text,
  shiprocket_courier text,
  created_at timestamptz not null default now()
);

create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists orders_order_number_idx on public.orders(order_number);
create index if not exists orders_razorpay_order_id_idx on public.orders(razorpay_order_id);
create index if not exists products_active_created_idx on public.products(active, created_at desc);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.admins enable row level security;
